# Generated by Django 4.1.2 on 2022-10-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text_field",
            new_name="text",
        ),
    ]
